### ISSUE TITLE
Is it possible to turn some tools into application???

### ISSUE THREAD

**Issue by MarcSteven** [mxcl/wishlist#11]

**Comment by mxcl** [comment]
Sorry, I do not understand this question.

**Comment by mxcl** [comment]
Reopen if you clarify.

**Comment by mxcl** [comment]
Sorry, I still don’t understand.

**Comment by mxcl** [comment]
What features? What tools? What applications?

**Comment by MarcSteven** [comment]
About the notification from Github ,till now I cannot find useful tool to monitor the notification ,so I think it's a cool feature  @mxcl

**Comment by mxcl** [comment]
**What** feature?

**Comment by MarcSteven** [comment]
Notification -When the  issue had some updates ,notice user to know ,I think it's cool feature ,but nowadays I cannot find the application ,I know there is lot of client to reviews it ,I know the website is existing ,but it's not great way to deal with it..How do you think

**Comment by mxcl** [comment]
I’m sorry I cannot understand what you are asking for or to which product you are referring to. Please enter text in your native language and I will get a translation.

**Comment by MarcSteven** [comment]
I means turning a good feature into GUI application.
For instance ,I always missed important notification I opened or discussed ,once updated ,notice me timely....

**Comment by mxcl** [comment]
Please type your request in your native language and I’ll get a translation.
